local state = require("state")

describe("state", function()
    it("initializes with menu state", function()
        state.init()
        expect_eq(state.current, "menu")
        expect_eq(state.previous, nil)
    end)

    it("can change state", function()
        state.init()
        state.set("racing")
        expect_eq(state.current, "racing")
        expect_eq(state.previous, "menu")
    end)

    it("is() returns true for current state", function()
        state.init()
        expect_true(state.is("menu"))
        expect_false(state.is("racing"))
        
        state.set("racing")
        expect_true(state.is("racing"))
        expect_false(state.is("menu"))
    end)

    it("goBack() returns to previous state", function()
        state.init()
        state.set("racing")
        state.set("paused")
        expect_eq(state.current, "paused")
        expect_eq(state.previous, "racing")
        
        state.goBack()
        expect_eq(state.current, "racing")
        expect_eq(state.previous, nil)
    end)

    it("goBack() does nothing if no previous state", function()
        state.init()
        expect_eq(state.previous, nil)
        state.goBack()
        expect_eq(state.current, "menu")
    end)

    it("tracks state transitions correctly", function()
        state.init()
        state.set("racing")
        state.set("paused")
        state.set("controls")
        
        expect_eq(state.current, "controls")
        expect_eq(state.previous, "paused")
    end)
end)
