local pause = require("pause")

describe("pause", function()
    it("initializes with first option selected", function()
        pause.init()
        expect_eq(pause.selectedIndex, 1)
    end)

    it("has three options", function()
        local options = pause.getOptions()
        expect_eq(#options, 3)
        expect_eq(options[1], "Resume")
        expect_eq(options[2], "Controls")
        expect_eq(options[3], "Main Menu")
    end)

    it("moveDown increments selected index", function()
        pause.init()
        pause.moveDown()
        expect_eq(pause.selectedIndex, 2)
        pause.moveDown()
        expect_eq(pause.selectedIndex, 3)
    end)

    it("moveDown wraps around", function()
        pause.init()
        pause.moveDown()
        pause.moveDown()
        pause.moveDown()
        expect_eq(pause.selectedIndex, 1)
    end)

    it("moveUp decrements selected index", function()
        pause.init()
        pause.selectedIndex = 2
        pause.moveUp()
        expect_eq(pause.selectedIndex, 1)
    end)

    it("moveUp wraps around", function()
        pause.init()
        pause.moveUp()
        expect_eq(pause.selectedIndex, 3)
    end)

    it("getSelected returns current option name", function()
        pause.init()
        expect_eq(pause.getSelected(), "Resume")
        pause.moveDown()
        expect_eq(pause.getSelected(), "Controls")
        pause.moveDown()
        expect_eq(pause.getSelected(), "Main Menu")
    end)

    it("getSelectedIndex returns current index", function()
        pause.init()
        expect_eq(pause.getSelectedIndex(), 1)
        pause.moveDown()
        expect_eq(pause.getSelectedIndex(), 2)
    end)
end)
